openapi: 3.0.0
info:
  title: Account Transaction Service
  version: 1.0.0
  description: Manage account transactions such as deposits, withdrawals, and transfers.

servers:
  - url: http://localhost:8085/api/v1

paths:
  /accounts/{accountId}/deposit:
    post:
      summary: Create a new deposit transaction.
      operationId: depositTransaction
      tags:
        - Transaction
      parameters:
        - name: accountId
          in: path
          required: true
          description: The account ID.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '201':
          description: Transaction created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request.
        '404':
          description: Account not found.
        '500':
          description: Internal server error.

  /accounts/{accountId}/withdrawal:
    post:
      summary: Create a new withdrawal transaction.
      operationId: withdrawalTransaction
      tags:
        - Transaction
      parameters:
        - name: accountId
          in: path
          required: true
          description: The account ID.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '201':
          description: Transaction created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request.
        '404':
          description: Account not found.
        '500':
          description: Internal server error.

  /accounts/transfer:
    post:
      summary: Make a transfer between accounts.
      operationId: makeTransfer
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Transfer completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
        '400':
          description: Invalid transfer request.
        '404':
          description: Account not found.
        '500':
          description: Internal server error.

components:
  schemas:
    TransactionRequest:
      type: object
      required:
        - amount
        - transactionType
      properties:
        amount:
          type: number
          format: double
          minimum: 0.01
          description: The transaction amount.
        transactionType:
          type: string
          enum:
            - deposit
            - withdrawal
          description: The transaction type.

    TransactionResponse:
      type: object
      required:
        - id
        - accountId
        - amount
        - transactionType
        - createdAt
      properties:
        id:
          type: string
          description: The transaction ID.
        accountId:
          type: string
          description: The account ID.
        amount:
          type: number
          format: double
          description: The transaction amount.
        transactionType:
          type: string
          enum:
            - deposit
            - withdrawal
          description: The transaction type.
        createdAt:
          type: string
          format: date-time
          description: The transaction creation date.

    TransferRequest:
      type: object
      required:
        - fromAccountId
        - toAccountId
        - amount
      properties:
        fromAccountId:
          type: string
          description: The ID of the account from which the funds are to be transferred.
        toAccountId:
          type: string
          description: The ID of the account to which the funds are to be transferred.
        amount:
          type: number
          format: double
          minimum: 0.01
          description: The amount of money to be transferred.
    TransferDetails:
      type: object
      required:
        - fromAccountId
        - toAccountId
      properties:
        fromAccountId:
          type: string
          description: The ID of the account from which the funds are to be transferred.
        toAccountId:
          type: string
          description: The ID of the account to which the funds are to be transferred.
    TransferResponse:
      type: object
      required:
        - id
        - type
        - amount
        - transactionDate
        - transferDetails
      properties:
        id:
          type: string
          description: The transaction ID.
        type:
          type: string
          enum:
            - transfer
          description: The transaction type.
        amount:
          type: number
          format: double
          description: The transaction amount.
        transactionDate:
          type: string
          format: date-time
          description: The transaction creation date.
        transferDetails:
          $ref: '#/components/schemas/TransferDetails'