openapi: 3.0.0
info:
  title: Account Transaction Service
  version: 1.0.0
  description: Manage account transactions such as deposits, withdrawals, and transfers.

servers:
  - url: http://localhost:8085/api/v1

paths:
  /accounts/{accountId}/deposit:
    post:
      summary: Create a new deposit transaction.
      operationId: depositTransaction
      tags:
        - Transactions
      parameters:
        - name: accountId
          in: path
          required: true
          description: The account ID.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '201':
          description: Transaction created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request.
        '404':
          description: Account not found.
        '500':
          description: Internal server error.

  /accounts/{accountId}/withdrawal:
    post:
      summary: Create a new withdrawal transaction.
      operationId: withdrawalTransaction
      tags:
        - Transactions
      parameters:
        - name: accountId
          in: path
          required: true
          description: The account ID.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '201':
          description: Transaction created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request.
        '404':
          description: Account not found.
        '500':
          description: Internal server error.

  /accounts/transfer:
    post:
      summary: Make a transfer between accounts.
      operationId: makeTransfer
      tags:
        - Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Transfer completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
        '400':
          description: Invalid transfer request.
        '404':
          description: Account not found.
        '500':
          description: Internal server error.

  /accounts/{ownerId}/transactions:
    get:
      summary: Retrieve transactions for a specific account.
      operationId: getAccountTransactions
      tags:
        - Transactions
      parameters:
        - name: ownerId
          in: path
          required: true
          description: The unique ID of the account owner for which to retrieve transactions.
          schema:
            type: string
        - name: transactionType
          in: query
          required: false
          description: Filter transactions by type (deposit, withdrawal, transfer).
          schema:
            type: string
            enum:
              - deposit
              - withdrawal
              - transfer
      responses:
        '200':
          description: A list of transactions retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request.
        '404':
          description: Account not found.
        '500':
          description: Internal server error.

components:
  schemas:
    TransactionRequest:
      type: object
      required:
        - amount
        - transactionType
      properties:
        amount:
          type: number
          format: double
          minimum: 0.01
          description: The transaction amount.
        transactionType:
          type: string
          enum:
            - deposit
            - withdrawal
          description: The type of transaction.

    TransactionResponse:
      type: object
      required:
        - id
        - accountId
        - amount
        - ownerId
        - transactionType
        - createdAt
      properties:
        id:
          type: string
          description: The transaction ID.
        accountId:
          type: string
          description: The account ID.
        ownerId:
          type: string
          description: The owner account ID.
        amount:
          type: number
          format: double
          description: The amount of the transaction.
        transactionType:
          type: string
          enum:
            - deposit
            - withdrawal
            - transfer
          description: The type of transaction.
        createdAt:
          type: string
          format: date-time
          description: The date and time when the transaction was created.
        transferDetails:
          $ref: '#/components/schemas/TransferDetails'
    TransferRequest:
      type: object
      required:
        - fromAccountId
        - toAccountId
        - amount
      properties:
        fromAccountId:
          type: string
          description: The ID of the account from which the funds are to be transferred.
        toAccountId:
          type: string
          description: The ID of the account to which the funds are to be transferred.
        amount:
          type: number
          format: double
          minimum: 0.01
          description: The amount of money to be transferred.

    TransferResponse:
      type: object
      required:
        - id
        - amount
        - ownerId
        - transactionDate
        - transferDetails
      properties:
        id:
          type: string
          description: The transaction ID.
        amount:
          type: number
          format: double
          description: The amount transferred.
        ownerId:
          type: string
          description: Owner Id.
        transactionDate:
          type: string
          format: date-time
          description: The date and time of the transaction.
        transferDetails:
          $ref: '#/components/schemas/TransferDetails'

    TransferDetails:
      type: object
      required:
        - fromAccountId
        - toAccountId
      properties:
        fromAccountId:
          type: string
          description: The ID of the account from which the funds are to be transferred.
        toAccountId:
          type: string
          description: The ID of the account to which the funds are to be transferred.